/**
 * FitCore — Day 49: Formal API Scope Registry & Hierarchy
 */

import { ApiScope, ApiScopeDefinition } from '@fitcore/types';

export const API_SCOPE_REGISTRY: Record<ApiScope, ApiScopeDefinition> = {
  'members:read': {
    scope: 'members:read',
    resource: 'members',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Member Profiles',
    description: 'Read member names, contact details, joined dates, and active status.',
    requiresExplicitConsent: false,
  },
  'members:write': {
    scope: 'members:write',
    resource: 'members',
    operation: 'write',
    sensitivity: 'STANDARD',
    displayName: 'Modify Member Profiles',
    description: 'Create and update member profile information.',
    requiresExplicitConsent: false,
  },
  'memberships:read': {
    scope: 'memberships:read',
    resource: 'memberships',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Membership Plans',
    description: 'View active membership tiers, pricing, and entitlements.',
    requiresExplicitConsent: false,
  },
  'memberships:write': {
    scope: 'memberships:write',
    resource: 'memberships',
    operation: 'write',
    sensitivity: 'SENSITIVE',
    displayName: 'Modify Memberships',
    description: 'Assign or alter member subscriptions.',
    requiresExplicitConsent: true,
  },
  'classes:read': {
    scope: 'classes:read',
    resource: 'classes',
    operation: 'read',
    sensitivity: 'PUBLIC',
    displayName: 'Read Class Schedules',
    description: 'View class sessions, schedules, room allocations, and capacity.',
    requiresExplicitConsent: false,
  },
  'classes:write': {
    scope: 'classes:write',
    resource: 'classes',
    operation: 'write',
    sensitivity: 'SENSITIVE',
    displayName: 'Manage Classes',
    description: 'Schedule, modify, or cancel gym classes.',
    requiresExplicitConsent: true,
  },
  'bookings:read': {
    scope: 'bookings:read',
    resource: 'bookings',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Bookings',
    description: 'View class and appointment bookings.',
    requiresExplicitConsent: false,
  },
  'bookings:write': {
    scope: 'bookings:write',
    resource: 'bookings',
    operation: 'write',
    sensitivity: 'STANDARD',
    displayName: 'Create and Cancel Bookings',
    description: 'Book sessions for members and cancel existing bookings.',
    requiresExplicitConsent: false,
  },
  'attendance:read': {
    scope: 'attendance:read',
    resource: 'attendance',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Attendance',
    description: 'View attendance records and check-in history.',
    requiresExplicitConsent: false,
  },
  'attendance:write': {
    scope: 'attendance:write',
    resource: 'attendance',
    operation: 'write',
    sensitivity: 'STANDARD',
    displayName: 'Record Check-Ins',
    description: 'Record member check-ins and attendance updates.',
    requiresExplicitConsent: false,
  },
  'trainers:read': {
    scope: 'trainers:read',
    resource: 'trainers',
    operation: 'read',
    sensitivity: 'PUBLIC',
    displayName: 'Read Trainer Profiles',
    description: 'View staff trainer bios, specialties, and public availability.',
    requiresExplicitConsent: false,
  },
  'training:read': {
    scope: 'training:read',
    resource: 'training',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Workout Plans',
    description: 'View general workout programs and exercise templates.',
    requiresExplicitConsent: false,
  },
  'training:write': {
    scope: 'training:write',
    resource: 'training',
    operation: 'write',
    sensitivity: 'STANDARD',
    displayName: 'Manage Workout Plans',
    description: 'Assign or modify workout programs.',
    requiresExplicitConsent: false,
  },
  'payments:read': {
    scope: 'payments:read',
    resource: 'payments',
    operation: 'read',
    sensitivity: 'SENSITIVE',
    displayName: 'Read Transactions',
    description: 'View payment receipts and transaction records (no card numbers or secrets).',
    requiresExplicitConsent: true,
  },
  'invoices:read': {
    scope: 'invoices:read',
    resource: 'invoices',
    operation: 'read',
    sensitivity: 'SENSITIVE',
    displayName: 'Read Invoices',
    description: 'View financial invoice records and billing status.',
    requiresExplicitConsent: true,
  },
  'communication:read': {
    scope: 'communication:read',
    resource: 'communication',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Messages',
    description: 'View message delivery status and notification history.',
    requiresExplicitConsent: false,
  },
  'communication:write': {
    scope: 'communication:write',
    resource: 'communication',
    operation: 'write',
    sensitivity: 'STANDARD',
    displayName: 'Send Messages',
    description: 'Trigger outbound transactional notifications.',
    requiresExplicitConsent: false,
  },
  'resources:read': {
    scope: 'resources:read',
    resource: 'resources',
    operation: 'read',
    sensitivity: 'STANDARD',
    displayName: 'Read Gym Resources',
    description: 'View physical studios, rooms, and equipment inventory.',
    requiresExplicitConsent: false,
  },
  'analytics:read': {
    scope: 'analytics:read',
    resource: 'analytics',
    operation: 'read',
    sensitivity: 'SENSITIVE',
    displayName: 'Read Business Metrics',
    description: 'View aggregated high-level business intelligence statistics.',
    requiresExplicitConsent: true,
  },
  'webhooks:manage': {
    scope: 'webhooks:manage',
    resource: 'webhooks',
    operation: 'manage',
    sensitivity: 'STANDARD',
    displayName: 'Manage Webhook Subscriptions',
    description: 'Create, update, and rotate webhook subscription endpoints.',
    requiresExplicitConsent: false,
  },
  'health:read': {
    scope: 'health:read',
    resource: 'health',
    operation: 'read',
    sensitivity: 'RESTRICTED',
    displayName: 'Read Health & PAR-Q Records',
    description: 'Access sensitive health clearance, medical notes, and PAR-Q disclosures.',
    requiresExplicitConsent: true,
  },
  'health:write': {
    scope: 'health:write',
    resource: 'health',
    operation: 'write',
    sensitivity: 'RESTRICTED',
    displayName: 'Modify Health Records',
    description: 'Record health assessments and physical medical notes.',
    requiresExplicitConsent: true,
  },
  'wearables:read': {
    scope: 'wearables:read',
    resource: 'wearables',
    operation: 'read',
    sensitivity: 'RESTRICTED',
    displayName: 'Read Wearable Biometrics',
    description: 'Read member heart rate, step count, and wearable telemetry with explicit member consent.',
    requiresExplicitConsent: true,
  },
};
