/**
 * FitCore — Day 42: Recurring Billing & Collections Constants
 */

export const RECURRING_BILLING_AUDIT = {
  SCHEDULE_CREATED: 'BILLING_SCHEDULE_CREATED',
  SCHEDULE_UPDATED: 'BILLING_SCHEDULE_UPDATED',
  SCHEDULE_PAUSED: 'BILLING_SCHEDULE_PAUSED',
  SCHEDULE_RESUMED: 'BILLING_SCHEDULE_RESUMED',
  SCHEDULE_CANCELLED: 'BILLING_SCHEDULE_CANCELLED',
  CYCLE_CREATED: 'BILLING_CYCLE_CREATED',
  PAYMENT_ATTEMPT_CREATED: 'PAYMENT_ATTEMPT_CREATED',
  PAYMENT_RETRY_TRIGGERED: 'PAYMENT_RETRY_TRIGGERED',
  DUNNING_CASE_CREATED: 'DUNNING_CASE_CREATED',
  DUNNING_STEP_EXECUTED: 'DUNNING_STEP_EXECUTED',
  DUNNING_ESCALATED: 'DUNNING_ESCALATED',
  DUNNING_RESOLVED: 'DUNNING_RESOLVED',
  COLLECTION_TASK_CREATED: 'COLLECTION_TASK_CREATED',
  COLLECTION_TASK_ASSIGNED: 'COLLECTION_TASK_ASSIGNED',
  COLLECTION_TASK_COMPLETED: 'COLLECTION_TASK_COMPLETED',
  PAYMENT_METHOD_UPDATED: 'PAYMENT_METHOD_UPDATED',
  FINANCIAL_COLLECTION_VIEWED: 'FINANCIAL_COLLECTION_VIEWED',
} as const;

export const DEFAULT_BILLING_POLICY = {
  retryMaxAttempts: 4,
  retryIntervalsDays: [2, 3, 3], // Attempt 1: Day 0, Attempt 2: Day 2, Attempt 3: Day 5, Attempt 4: Day 8
  gracePeriodDays: 7,
  gracePeriodAccessAllowed: true,
  dunningAutoEscalateDays: 14,
  dunningMaxPeriodDays: 30,
  communicationChannels: ['EMAIL', 'IN_APP'],
};
