/**
 * FitCore — Day 50: Marketplace Audit & Event Actions
 */

export const MARKETPLACE_ACTIONS = {
  LISTING_CREATED: 'LISTING_CREATED',
  LISTING_UPDATED: 'LISTING_UPDATED',
  LISTING_SUBMITTED: 'LISTING_SUBMITTED',
  LISTING_APPROVED: 'LISTING_APPROVED',
  LISTING_REJECTED: 'LISTING_REJECTED',
  LISTING_PUBLISHED: 'LISTING_PUBLISHED',
  LISTING_SUSPENDED: 'LISTING_SUSPENDED',
  LISTING_DEPRECATED: 'LISTING_DEPRECATED',
  VERSION_CREATED: 'VERSION_CREATED',
  VERSION_PUBLISHED: 'VERSION_PUBLISHED',
  APP_INSTALLED: 'APP_INSTALLED',
  APP_CONFIGURED: 'APP_CONFIGURED',
  APP_PAUSED: 'APP_PAUSED',
  APP_RESUMED: 'APP_RESUMED',
  APP_UPGRADED: 'APP_UPGRADED',
  APP_UNINSTALLED: 'APP_UNINSTALLED',
  PERMISSIONS_GRANTED: 'PERMISSIONS_GRANTED',
  PERMISSIONS_REVOKED: 'PERMISSIONS_REVOKED',
  HEALTH_PII_CONSENTED: 'HEALTH_PII_CONSENTED',
  REVIEW_CREATED: 'REVIEW_CREATED',
  REVIEW_MODERATED: 'REVIEW_MODERATED',
  REVIEW_FLAGGED: 'REVIEW_FLAGGED',
  HEALTH_CHECK_FAILED: 'HEALTH_CHECK_FAILED',
} as const;

export type MarketplaceAction = (typeof MARKETPLACE_ACTIONS)[keyof typeof MARKETPLACE_ACTIONS];
