export const NUTRITION_COACH_FEATURE = 'NUTRITION_COACH' as const;

export const NUTRITION_COACH_PROMPT_KEY = 'nutrition_coach.v1';
export const NUTRITION_COACH_PROMPT_VERSION = 1;

export const NUTRITION_CONTEXT_TTL_SECONDS = 300; // 5 minutes cache
export const NUTRITION_DAILY_SUMMARY_TTL_SECONDS = 300;

export const DEFAULT_COACHING_STYLE = 'SUPPORTIVE';
export const DEFAULT_RESPONSE_LENGTH = 'BALANCED';
export const DEFAULT_UNIT_PREFERENCE = 'METRIC';
export const DEFAULT_LANGUAGE = 'en';

export const MAX_RECENT_FOOD_LOGS_CONTEXT = 10;
export const MAX_CONVERSATION_HISTORY_TURNS = 6;
export const CONVERSATION_SUMMARY_INTERVAL_TURNS = 10;
