/**
 * Day 35 — AI Receptionist Production Workflow Constants & Defaults
 */

import {
  WorkflowHandoffPriority,
  WorkflowHandoffReason,
  ReceptionistOutcome,
} from '@fitcore/types';

export const RECEPTIONIST_WORKFLOW_DEFAULTS = {
  LOOP_PROTECTION: {
    maxFailures: 3,
    maxToolCalls: 3,
    maxTurns: 20,
    maxEscalationAttempts: 2,
  },
  DEFAULT_TIMEZONE: 'Asia/Kathmandu',
  DEFAULT_LANGUAGE: 'en',
  BUSINESS_RULES: {
    requireHumanForPricing: true,
    requireHumanForComplaints: true,
    requireVerificationForMemberData: true,
    requireConfirmationForBookingMutation: true,
    requireConsentForMarketing: true,
  },
};

export const RECEPTIONIST_AUDIT_ACTIONS = {
  INTERACTION_VIEWED: 'RECEPTIONIST_INTERACTION_VIEWED',
  HANDOFF_VIEWED: 'RECEPTIONIST_HANDOFF_VIEWED',
  HANDOFF_CREATED: 'RECEPTIONIST_HANDOFF_CREATED',
  HANDOFF_ASSIGNED: 'RECEPTIONIST_HANDOFF_ASSIGNED',
  HANDOFF_ACCEPTED: 'RECEPTIONIST_HANDOFF_ACCEPTED',
  HANDOFF_COMPLETED: 'RECEPTIONIST_HANDOFF_COMPLETED',
  FOLLOWUP_CREATED: 'RECEPTIONIST_FOLLOWUP_CREATED',
  FOLLOWUP_COMPLETED: 'RECEPTIONIST_FOLLOWUP_COMPLETED',
  TRANSCRIPT_VIEWED: 'RECEPTIONIST_TRANSCRIPT_VIEWED',
  RECORDING_VIEWED: 'RECEPTIONIST_RECORDING_VIEWED',
  CONFIGURATION_UPDATED: 'RECEPTIONIST_CONFIGURATION_UPDATED',
  AI_SUMMARY_GENERATED: 'RECEPTIONIST_AI_SUMMARY_GENERATED',
  ESCALATION_TRIGGERED: 'RECEPTIONIST_ESCALATION_TRIGGERED',
  CALLBACK_REQUESTED: 'RECEPTIONIST_CALLBACK_REQUESTED',
  MISSED_CALL_RECORDED: 'RECEPTIONIST_MISSED_CALL_RECORDED',
};

export const HANDOFF_REASON_PRIORITY_MAP: Record<WorkflowHandoffReason, WorkflowHandoffPriority> = {
  COMPLAINT: 'HIGH',
  POLICY_EXCEPTION: 'HIGH',
  PRICING_EXCEPTION: 'HIGH',
  TECHNICAL_FAILURE: 'HIGH',
  TOOL_FAILURE: 'HIGH',
  BOOKING_FAILURE: 'HIGH',
  SPECIAL_REQUEST: 'NORMAL',
  PAYMENT_QUESTION: 'NORMAL',
  MEMBERSHIP_EXCEPTION: 'NORMAL',
  COMPLEX_REQUEST: 'NORMAL',
  CUSTOMER_REQUESTED: 'NORMAL',
  IDENTITY_VERIFICATION: 'NORMAL',
  LOW_CONFIDENCE: 'LOW',
  OTHER: 'NORMAL',
};

export const OUTCOME_RESOLUTION_MAP: Record<string, ReceptionistOutcome> = {
  BOOKING_SUCCESS: 'BOOKING_CREATED',
  BOOKING_CANCELLED: 'BOOKING_CANCELLED',
  BOOKING_RESCHEDULED: 'BOOKING_RESCHEDULED',
  WAITLIST_JOINED: 'WAITLIST_JOINED',
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_QUALIFIED: 'LEAD_QUALIFIED',
  STAFF_HANDOFF: 'STAFF_HANDOFF',
  CALLBACK_REQUESTED: 'CALLBACK_REQUESTED',
  INFORMATION_PROVIDED: 'INFORMATION_PROVIDED',
  UNRESOLVED: 'UNRESOLVED',
  FAILED: 'FAILED',
};
