/**
 * Constants for FitCore AI Retention Intelligence (Day 26)
 */

export const RETENTION_INTELLIGENCE_FEATURE = 'RETENTION_INTELLIGENCE';
export const RETENTION_INTELLIGENCE_PROMPT_KEY = 'retention_intelligence.v1';
export const RETENTION_INTELLIGENCE_PROMPT_VERSION = 1;

// Cache TTL
export const RETENTION_ANALYSIS_CACHE_TTL_SECONDS = 3600; // 1 hour default
export const RETENTION_RISK_CACHE_TTL_SECONDS = 1800;     // 30 minutes
export const RETENTION_QUEUE_CACHE_TTL_SECONDS = 300;      // 5 minutes

// Domain Events (Internal Event Bus / Observability)
export const RETENTION_EVENTS = {
  RISK_CREATED: 'RETENTION_RISK_CREATED',
  RISK_ESCALATED: 'RETENTION_RISK_ESCALATED',
  RISK_REDUCED: 'RETENTION_RISK_REDUCED',
  REENGAGEMENT_DETECTED: 'MEMBER_REENGAGEMENT_DETECTED',
  FOLLOWUP_CREATED: 'RETENTION_FOLLOWUP_CREATED',
  FOLLOWUP_COMPLETED: 'RETENTION_FOLLOWUP_COMPLETED',
} as const;

// Audit Event Actions (Auditing without sensitive medical/health leaks)
export const RETENTION_AUDIT_ACTIONS = {
  ANALYSIS_VIEWED: 'RETENTION_ANALYSIS_VIEWED',
  RISK_VIEWED: 'RETENTION_RISK_VIEWED',
  RECOMMENDATION_GENERATED: 'RETENTION_RECOMMENDATION_GENERATED',
  FOLLOWUP_CREATED: 'RETENTION_FOLLOWUP_CREATED',
  FOLLOWUP_UPDATED: 'RETENTION_FOLLOWUP_UPDATED',
  FOLLOWUP_COMPLETED: 'RETENTION_FOLLOWUP_COMPLETED',
  FEEDBACK_SUBMITTED: 'RETENTION_AI_FEEDBACK_SUBMITTED',
} as const;

// Authorized Staff Roles for Retention Intelligence
export const RETENTION_STAFF_ROLES = [
  'SUPERADMIN',
  'ORGANISATION_OWNER',
  'OUTLET_MANAGER',
  'TRAINER',
  'RECEPTION',
] as const;

// Controlled Retention Intervention Taxonomy
export const RETENTION_INTERVENTION_TYPES = [
  'TRAINER_CHECK_IN',
  'GOAL_REVIEW',
  'TRAINING_RESTART',
  'CLASS_RECOMMENDATION',
  'PERSONAL_TRAINING_FOLLOW_UP',
  'RECOVERY_SUPPORT',
  'APP_ENGAGEMENT',
  'NUTRITION_ENGAGEMENT',
  'MEMBERSHIP_CONVERSATION',
  'GENERAL_SUPPORT',
  'NO_ACTION',
  'INSUFFICIENT_DATA',
] as const;

