export const ERROR_CODES = {
  // Network & System
  NETWORK_UNAVAILABLE: 'NETWORK_UNAVAILABLE',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  SERVER_ERROR: 'SERVER_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // Authentication & Session
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_FAILED: 'AUTH_REFRESH_FAILED',
  AUTH_SESSION_TERMINATED: 'AUTH_SESSION_TERMINATED',

  // Authorization & Multi-tenancy
  FORBIDDEN: 'FORBIDDEN',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  OUTLET_ACCESS_DENIED: 'OUTLET_ACCESS_DENIED',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // Storage
  STORAGE_READ_ERROR: 'STORAGE_READ_ERROR',
  STORAGE_WRITE_ERROR: 'STORAGE_WRITE_ERROR',

  // Integrations
  HEALTH_PERMISSIONS_DENIED: 'HEALTH_PERMISSIONS_DENIED',
  AI_QUOTA_EXCEEDED: 'AI_QUOTA_EXCEEDED',

  // Day 11: Staff & Trainer Management
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  STAFF_INACTIVE: 'STAFF_INACTIVE',
  STAFF_ALREADY_EXISTS: 'STAFF_ALREADY_EXISTS',
  TRAINER_NOT_FOUND: 'TRAINER_NOT_FOUND',
  TRAINER_INACTIVE: 'TRAINER_INACTIVE',
  CERTIFICATION_NOT_FOUND: 'CERTIFICATION_NOT_FOUND',
  CERTIFICATION_EXPIRED: 'CERTIFICATION_EXPIRED',
  INVITATION_NOT_FOUND: 'INVITATION_NOT_FOUND',
  INVITATION_EXPIRED: 'INVITATION_EXPIRED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',
  CLIENT_ASSIGNMENT_EXISTS: 'CLIENT_ASSIGNMENT_EXISTS',
  TRAINER_ASSIGNMENT_NOT_ALLOWED: 'TRAINER_ASSIGNMENT_NOT_ALLOWED',
  PRIMARY_TRAINER_EXISTS: 'PRIMARY_TRAINER_EXISTS',
  CROSS_TENANT_ASSIGNMENT_FORBIDDEN: 'CROSS_TENANT_ASSIGNMENT_FORBIDDEN',

  // Day 12: Personal Training & Coaching
  TRAINING_PROGRAM_NOT_FOUND: 'TRAINING_PROGRAM_NOT_FOUND',
  TRAINING_PROGRAM_INVALID_STATE: 'TRAINING_PROGRAM_INVALID_STATE',
  TRAINING_GOAL_NOT_FOUND: 'TRAINING_GOAL_NOT_FOUND',
  TRAINER_NOTE_NOT_FOUND: 'TRAINER_NOTE_NOT_FOUND',
  TRAINER_NOTE_ACCESS_DENIED: 'TRAINER_NOTE_ACCESS_DENIED',
  TRAINING_SESSION_NOT_FOUND: 'TRAINING_SESSION_NOT_FOUND',
  TRAINING_SESSION_CONFLICT: 'TRAINING_SESSION_CONFLICT',
  TRAINER_UNAVAILABLE: 'TRAINER_UNAVAILABLE',
  TRAINER_NOT_ASSIGNED: 'TRAINER_NOT_ASSIGNED',
  MEMBER_NOT_AUTHORIZED: 'MEMBER_NOT_AUTHORIZED',
  SESSION_ALREADY_COMPLETED: 'SESSION_ALREADY_COMPLETED',

  // Day 13: Exercise Library & Workout Programming
  EXERCISE_NOT_FOUND: 'EXERCISE_NOT_FOUND',
  EXERCISE_SYSTEM_IMMUTABLE: 'EXERCISE_SYSTEM_IMMUTABLE',
  EXERCISE_ARCHIVED: 'EXERCISE_ARCHIVED',
  WORKOUT_TEMPLATE_NOT_FOUND: 'WORKOUT_TEMPLATE_NOT_FOUND',
  WORKOUT_TEMPLATE_ARCHIVED: 'WORKOUT_TEMPLATE_ARCHIVED',
  WORKOUT_NOT_FOUND: 'WORKOUT_NOT_FOUND',
  WORKOUT_INVALID_STATE: 'WORKOUT_INVALID_STATE',
  WORKOUT_ALREADY_COMPLETED: 'WORKOUT_ALREADY_COMPLETED',
  WORKOUT_EXERCISE_NOT_FOUND: 'WORKOUT_EXERCISE_NOT_FOUND',
  WORKOUT_SET_NOT_FOUND: 'WORKOUT_SET_NOT_FOUND',
  DUPLICATE_SET_SUBMISSION: 'DUPLICATE_SET_SUBMISSION',
  INVALID_MEASUREMENT_UNIT: 'INVALID_MEASUREMENT_UNIT',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
