import type {
  PermissionAction,
  PermissionResource,
  PermissionRule,
  PermissionScope,
  UserRole,
} from '@fitcore/types';

export const PERMISSION_RESOURCES: readonly PermissionResource[] = [
  'members',
  'staff',
  'outlets',
  'organisations',
  'memberships',
  'payments',
  'invoices',
  'appointments',
  'classes',
  'workouts',
  'exercises',
  'health_data',
  'wearables',
  'ai',
  'reports',
  'retail',
  'door_access',
  'documents',
  'communications',
  'settings',
  'trainers',
  'certifications',
  'trainer_clients',
  'training_programs',
  'training_goals',
  'trainer_notes',
  'pt_sessions',
  'workout_templates',
  'training_plans',
  'progress',
  'assessments',
  'body_measurements',
  'personal_records',
  'nutrition',
  'nutrition_plans',
  'foods',
  'food_logs',
  'notifications',
  'engagement',
  'habits',
  'challenges',
  'rewards',
  'marketplace',
  'enterprise',
  'policies',
  'brands',
  'domains',
  'security',
  'privacy',
  'compliance',
] as const;

export const PERMISSION_ACTIONS: readonly PermissionAction[] = [
  'read',
  'write',
  'create',
  'update',
  'delete',
  'manage',
  'use',
  'configure',
  'export',
] as const;

export const PERMISSION_SCOPES: readonly PermissionScope[] = [
  'PLATFORM',
  'ORGANISATION',
  'BRAND',
  'REGION',
  'OUTLET',
  'ASSIGNED_CLIENTS',
  'SELF',
] as const;

/**
 * Baseline permission mappings by role
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, PermissionRule[]> = {
  SUPERADMIN: [
    { resource: 'organisations', action: 'manage', scope: 'PLATFORM' },
    { resource: 'outlets', action: 'manage', scope: 'PLATFORM' },
    { resource: 'members', action: 'manage', scope: 'PLATFORM' },
    { resource: 'staff', action: 'manage', scope: 'PLATFORM' },
    { resource: 'reports', action: 'export', scope: 'PLATFORM' },
    { resource: 'ai', action: 'manage', scope: 'PLATFORM' },
    { resource: 'training_programs', action: 'manage', scope: 'PLATFORM' },
    { resource: 'training_goals', action: 'manage', scope: 'PLATFORM' },
    { resource: 'trainer_notes', action: 'manage', scope: 'PLATFORM' },
    { resource: 'pt_sessions', action: 'manage', scope: 'PLATFORM' },
    { resource: 'exercises', action: 'manage', scope: 'PLATFORM' },
    { resource: 'workout_templates', action: 'manage', scope: 'PLATFORM' },
    { resource: 'workouts', action: 'manage', scope: 'PLATFORM' },
    { resource: 'progress', action: 'manage', scope: 'PLATFORM' },
    { resource: 'assessments', action: 'manage', scope: 'PLATFORM' },
    { resource: 'body_measurements', action: 'manage', scope: 'PLATFORM' },
    { resource: 'personal_records', action: 'manage', scope: 'PLATFORM' },
    { resource: 'nutrition', action: 'manage', scope: 'PLATFORM' },
    { resource: 'nutrition_plans', action: 'manage', scope: 'PLATFORM' },
    { resource: 'foods', action: 'manage', scope: 'PLATFORM' },
    { resource: 'food_logs', action: 'manage', scope: 'PLATFORM' },
    { resource: 'notifications', action: 'manage', scope: 'PLATFORM' },
    { resource: 'communications', action: 'manage', scope: 'PLATFORM' },
    { resource: 'engagement', action: 'manage', scope: 'PLATFORM' },
    { resource: 'habits', action: 'manage', scope: 'PLATFORM' },
    { resource: 'challenges', action: 'manage', scope: 'PLATFORM' },
    { resource: 'rewards', action: 'manage', scope: 'PLATFORM' },
    { resource: 'security', action: 'manage', scope: 'PLATFORM' },
    { resource: 'privacy', action: 'manage', scope: 'PLATFORM' },
    { resource: 'compliance', action: 'manage', scope: 'PLATFORM' },
  ],
  ORGANISATION_OWNER: [
    { resource: 'security', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'privacy', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'compliance', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'outlets', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'members', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'staff', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'memberships', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'payments', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'invoices', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'read', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'export', scope: 'ORGANISATION' },
    { resource: 'ai', action: 'configure', scope: 'ORGANISATION' },
    { resource: 'ai', action: 'read', scope: 'ORGANISATION' },
    { resource: 'trainers', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'certifications', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'trainer_clients', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'training_programs', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'training_goals', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'trainer_notes', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'pt_sessions', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'exercises', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'workouts', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'workout_templates', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'training_plans', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'progress', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'assessments', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'body_measurements', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'personal_records', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'nutrition', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'nutrition_plans', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'foods', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'food_logs', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'notifications', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'communications', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'engagement', action: 'read', scope: 'ORGANISATION' },
    { resource: 'habits', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'challenges', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'rewards', action: 'manage', scope: 'ORGANISATION' },
  ],
  OUTLET_MANAGER: [
    { resource: 'members', action: 'write', scope: 'OUTLET' },
    { resource: 'staff', action: 'read', scope: 'OUTLET' },
    { resource: 'appointments', action: 'manage', scope: 'OUTLET' },
    { resource: 'classes', action: 'manage', scope: 'OUTLET' },
    { resource: 'door_access', action: 'manage', scope: 'OUTLET' },
    { resource: 'retail', action: 'manage', scope: 'OUTLET' },
    { resource: 'reports', action: 'read', scope: 'OUTLET' },
    { resource: 'trainers', action: 'manage', scope: 'OUTLET' },
    { resource: 'certifications', action: 'read', scope: 'OUTLET' },
    { resource: 'trainer_clients', action: 'manage', scope: 'OUTLET' },
    { resource: 'training_programs', action: 'read', scope: 'OUTLET' },
    { resource: 'training_goals', action: 'read', scope: 'OUTLET' },
    { resource: 'trainer_notes', action: 'read', scope: 'OUTLET' },
    { resource: 'pt_sessions', action: 'manage', scope: 'OUTLET' },
    { resource: 'exercises', action: 'read', scope: 'ORGANISATION' },
    { resource: 'workouts', action: 'manage', scope: 'OUTLET' },
    { resource: 'workout_templates', action: 'read', scope: 'ORGANISATION' },
    { resource: 'training_plans', action: 'read', scope: 'OUTLET' },
    { resource: 'progress', action: 'read', scope: 'OUTLET' },
    { resource: 'assessments', action: 'manage', scope: 'OUTLET' },
    { resource: 'body_measurements', action: 'read', scope: 'OUTLET' },
    { resource: 'personal_records', action: 'read', scope: 'OUTLET' },
    { resource: 'nutrition', action: 'read', scope: 'OUTLET' },
    { resource: 'nutrition_plans', action: 'read', scope: 'OUTLET' },
    { resource: 'foods', action: 'read', scope: 'ORGANISATION' },
    { resource: 'food_logs', action: 'read', scope: 'OUTLET' },
    { resource: 'notifications', action: 'manage', scope: 'OUTLET' },
    { resource: 'communications', action: 'read', scope: 'OUTLET' },
    { resource: 'engagement', action: 'read', scope: 'OUTLET' },
    { resource: 'habits', action: 'read', scope: 'OUTLET' },
    { resource: 'challenges', action: 'manage', scope: 'OUTLET' },
    { resource: 'rewards', action: 'manage', scope: 'OUTLET' },
    { resource: 'ai', action: 'read', scope: 'OUTLET' },
  ],
  RECEPTION: [
    { resource: 'members', action: 'read', scope: 'OUTLET' },
    { resource: 'appointments', action: 'write', scope: 'OUTLET' },
    { resource: 'classes', action: 'write', scope: 'OUTLET' },
    { resource: 'door_access', action: 'write', scope: 'OUTLET' },
    { resource: 'retail', action: 'write', scope: 'OUTLET' },
    { resource: 'payments', action: 'create', scope: 'OUTLET' },
    { resource: 'trainers', action: 'read', scope: 'OUTLET' },
    { resource: 'pt_sessions', action: 'read', scope: 'OUTLET' },
    { resource: 'notifications', action: 'read', scope: 'OUTLET' },
    { resource: 'communications', action: 'read', scope: 'OUTLET' },
    { resource: 'engagement', action: 'read', scope: 'OUTLET' },
    { resource: 'challenges', action: 'read', scope: 'OUTLET' },
    { resource: 'rewards', action: 'read', scope: 'OUTLET' },
  ],
  TRAINER: [
    { resource: 'members', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'appointments', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'workouts', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'exercises', action: 'read', scope: 'ORGANISATION' },
    { resource: 'exercises', action: 'write', scope: 'ORGANISATION' },
    { resource: 'workout_templates', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'health_data', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'ai', action: 'use', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'trainers', action: 'read', scope: 'ORGANISATION' },
    { resource: 'trainers', action: 'update', scope: 'SELF' },
    { resource: 'certifications', action: 'read', scope: 'SELF' },
    { resource: 'certifications', action: 'manage', scope: 'SELF' },
    { resource: 'trainer_clients', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'training_programs', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'training_goals', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'trainer_notes', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'pt_sessions', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'training_plans', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'progress', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'assessments', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'body_measurements', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'personal_records', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'nutrition', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'nutrition_plans', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'foods', action: 'read', scope: 'ORGANISATION' },
    { resource: 'foods', action: 'write', scope: 'ORGANISATION' },
    { resource: 'food_logs', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'notifications', action: 'manage', scope: 'SELF' },
    { resource: 'communications', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'engagement', action: 'read', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'habits', action: 'manage', scope: 'ASSIGNED_CLIENTS' },
    { resource: 'challenges', action: 'read', scope: 'OUTLET' },
  ],
  FINANCE: [
    { resource: 'payments', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'invoices', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'export', scope: 'ORGANISATION' },
    { resource: 'memberships', action: 'read', scope: 'ORGANISATION' },
    { resource: 'notifications', action: 'manage', scope: 'SELF' },
    { resource: 'communications', action: 'read', scope: 'ORGANISATION' },
  ],
  MEMBER: [
    { resource: 'members', action: 'read', scope: 'SELF' },
    { resource: 'members', action: 'update', scope: 'SELF' },
    { resource: 'appointments', action: 'write', scope: 'SELF' },
    { resource: 'workouts', action: 'read', scope: 'SELF' },
    { resource: 'workouts', action: 'write', scope: 'SELF' },
    { resource: 'health_data', action: 'write', scope: 'SELF' },
    { resource: 'health_data', action: 'read', scope: 'SELF' },
    { resource: 'wearables', action: 'manage', scope: 'SELF' },
    { resource: 'payments', action: 'read', scope: 'SELF' },
    { resource: 'ai', action: 'use', scope: 'SELF' },
    { resource: 'documents', action: 'write', scope: 'SELF' },
    { resource: 'training_programs', action: 'read', scope: 'SELF' },
    { resource: 'training_goals', action: 'manage', scope: 'SELF' },
    { resource: 'trainer_notes', action: 'read', scope: 'SELF' },
    { resource: 'pt_sessions', action: 'read', scope: 'SELF' },
    { resource: 'exercises', action: 'read', scope: 'ORGANISATION' },
    { resource: 'workout_templates', action: 'read', scope: 'ORGANISATION' },
    { resource: 'training_plans', action: 'read', scope: 'SELF' },
    { resource: 'progress', action: 'read', scope: 'SELF' },
    { resource: 'assessments', action: 'read', scope: 'SELF' },
    { resource: 'body_measurements', action: 'manage', scope: 'SELF' },
    { resource: 'personal_records', action: 'read', scope: 'SELF' },
    { resource: 'nutrition', action: 'read', scope: 'SELF' },
    { resource: 'nutrition', action: 'write', scope: 'SELF' },
    { resource: 'nutrition_plans', action: 'read', scope: 'SELF' },
    { resource: 'foods', action: 'read', scope: 'ORGANISATION' },
    { resource: 'food_logs', action: 'manage', scope: 'SELF' },
    { resource: 'notifications', action: 'manage', scope: 'SELF' },
    { resource: 'communications', action: 'read', scope: 'SELF' },
    { resource: 'engagement', action: 'read', scope: 'SELF' },
    { resource: 'habits', action: 'manage', scope: 'SELF' },
    { resource: 'challenges', action: 'manage', scope: 'SELF' },
    { resource: 'rewards', action: 'manage', scope: 'SELF' },
    { resource: 'security', action: 'manage', scope: 'SELF' },
    { resource: 'privacy', action: 'manage', scope: 'SELF' },
  ],
  ENTERPRISE_ADMIN: [
    { resource: 'security', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'privacy', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'compliance', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'enterprise', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'policies', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'brands', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'domains', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'organisations', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'outlets', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'staff', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'export', scope: 'ORGANISATION' },
    { resource: 'settings', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'ai', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'marketplace', action: 'manage', scope: 'ORGANISATION' },
  ],
  REGIONAL_MANAGER: [
    { resource: 'enterprise', action: 'read', scope: 'REGION' },
    { resource: 'outlets', action: 'manage', scope: 'REGION' },
    { resource: 'staff', action: 'manage', scope: 'REGION' },
    { resource: 'members', action: 'read', scope: 'REGION' },
    { resource: 'classes', action: 'manage', scope: 'REGION' },
    { resource: 'reports', action: 'read', scope: 'REGION' },
    { resource: 'reports', action: 'export', scope: 'REGION' },
  ],
  BRAND_MANAGER: [
    { resource: 'enterprise', action: 'read', scope: 'BRAND' },
    { resource: 'brands', action: 'manage', scope: 'BRAND' },
    { resource: 'outlets', action: 'read', scope: 'BRAND' },
    { resource: 'reports', action: 'read', scope: 'BRAND' },
    { resource: 'settings', action: 'manage', scope: 'BRAND' },
  ],
  OPERATIONS_MANAGER: [
    { resource: 'outlets', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'staff', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'door_access', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'classes', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'read', scope: 'ORGANISATION' },
  ],
  COMPLIANCE_MANAGER: [
    { resource: 'privacy', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'compliance', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'enterprise', action: 'read', scope: 'ORGANISATION' },
    { resource: 'policies', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'export', scope: 'ORGANISATION' },
    { resource: 'documents', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'settings', action: 'read', scope: 'ORGANISATION' },
  ],
  ANALYTICS_MANAGER: [
    { resource: 'reports', action: 'manage', scope: 'ORGANISATION' },
    { resource: 'reports', action: 'export', scope: 'ORGANISATION' },
    { resource: 'members', action: 'read', scope: 'ORGANISATION' },
    { resource: 'outlets', action: 'read', scope: 'ORGANISATION' },
    { resource: 'payments', action: 'read', scope: 'ORGANISATION' },
  ],
};
