import type { UserRole } from '@fitcore/types';

export const ROLES: Record<UserRole, UserRole> = {
  SUPERADMIN: 'SUPERADMIN',
  ORGANISATION_OWNER: 'ORGANISATION_OWNER',
  OUTLET_MANAGER: 'OUTLET_MANAGER',
  RECEPTION: 'RECEPTION',
  TRAINER: 'TRAINER',
  FINANCE: 'FINANCE',
  MEMBER: 'MEMBER',
  ENTERPRISE_ADMIN: 'ENTERPRISE_ADMIN',
  REGIONAL_MANAGER: 'REGIONAL_MANAGER',
  BRAND_MANAGER: 'BRAND_MANAGER',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  COMPLIANCE_MANAGER: 'COMPLIANCE_MANAGER',
  ANALYTICS_MANAGER: 'ANALYTICS_MANAGER',
} as const;

export const ALL_ROLES: readonly UserRole[] = [
  ROLES.SUPERADMIN,
  ROLES.ORGANISATION_OWNER,
  ROLES.OUTLET_MANAGER,
  ROLES.RECEPTION,
  ROLES.TRAINER,
  ROLES.FINANCE,
  ROLES.MEMBER,
  ROLES.ENTERPRISE_ADMIN,
  ROLES.REGIONAL_MANAGER,
  ROLES.BRAND_MANAGER,
  ROLES.OPERATIONS_MANAGER,
  ROLES.COMPLIANCE_MANAGER,
  ROLES.ANALYTICS_MANAGER,
] as const;

export const STAFF_ROLES: readonly UserRole[] = [
  ROLES.ORGANISATION_OWNER,
  ROLES.OUTLET_MANAGER,
  ROLES.RECEPTION,
  ROLES.TRAINER,
  ROLES.FINANCE,
  ROLES.ENTERPRISE_ADMIN,
  ROLES.REGIONAL_MANAGER,
  ROLES.BRAND_MANAGER,
  ROLES.OPERATIONS_MANAGER,
  ROLES.COMPLIANCE_MANAGER,
  ROLES.ANALYTICS_MANAGER,
] as const;
