import { BusinessMetricDefinition } from '@fitcore/types';

export const CANONICAL_BUSINESS_METRICS: Record<string, BusinessMetricDefinition> = {
  // -------------------------------------------------------------
  // MEMBERSHIP DOMAIN
  // -------------------------------------------------------------
  'membership.active_members': {
    key: 'membership.active_members',
    domain: 'MEMBERSHIP',
    name: 'Active Members',
    description: 'Total number of distinct members with currently active memberships.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.new_members': {
    key: 'membership.new_members',
    domain: 'MEMBERSHIP',
    name: 'New Members',
    description: 'Count of members who activated their very first membership within the period.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.returning_members': {
    key: 'membership.returning_members',
    domain: 'MEMBERSHIP',
    name: 'Returning Members',
    description: 'Count of members who renewed or rejoined after an inactive lapse.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.reactivated_members': {
    key: 'membership.reactivated_members',
    domain: 'MEMBERSHIP',
    name: 'Reactivated Members',
    description: 'Count of members who were previously cancelled or expired and activated a new membership.',
    source: 'ReactivationService & MemberMembership',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.inactive_members': {
    key: 'membership.inactive_members',
    domain: 'MEMBERSHIP',
    name: 'Inactive Members',
    description: 'Registered member profiles without an active membership in the organisation.',
    source: 'MembershipsService (MemberProfile)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.suspended_members': {
    key: 'membership.suspended_members',
    domain: 'MEMBERSHIP',
    name: 'Suspended/Paused Members',
    description: 'Memberships currently placed in paused or suspended status.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.cancelled_members': {
    key: 'membership.cancelled_members',
    domain: 'MEMBERSHIP',
    name: 'Cancelled Members',
    description: 'Count of memberships terminated/cancelled within the period.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.expiring_members': {
    key: 'membership.expiring_members',
    domain: 'MEMBERSHIP',
    name: 'Expiring Memberships (Next 30 Days)',
    description: 'Active memberships scheduled to reach term end date within the next 30 days.',
    source: 'MembershipsService (MemberMembership)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.net_member_change': {
    key: 'membership.net_member_change',
    domain: 'MEMBERSHIP',
    name: 'Net Member Change',
    description: 'Deterministic net change in membership: New Members + Reactivated Members - Cancelled Members.',
    source: 'MembershipsService (Calculated)',
    aggregation: 'SUM',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'membership.growth_rate': {
    key: 'membership.growth_rate',
    domain: 'MEMBERSHIP',
    name: 'Membership Growth Rate',
    description: 'Percentage growth in active memberships over previous period baseline.',
    source: 'MembershipsService (Calculated)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
    dataQualityRequirements: {
      minimumSampleThreshold: 1,
      caveats: ['Requires non-zero baseline active member count in prior period.'],
    },
  },

  // -------------------------------------------------------------
  // RETENTION DOMAIN
  // -------------------------------------------------------------
  'retention.retention_rate': {
    key: 'retention.retention_rate',
    domain: 'RETENTION',
    name: 'Member Retention Rate',
    description: 'Percentage of starting members retained through the period: (End Active - New) / Start Active * 100.',
    source: 'RetentionIntelligence (Calculated)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'retention.churn_rate': {
    key: 'retention.churn_rate',
    domain: 'RETENTION',
    name: 'Membership Churn Rate',
    description: 'Percentage of starting active members who cancelled during the period.',
    source: 'RetentionIntelligence (Calculated)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'retention.high_risk_count': {
    key: 'retention.high_risk_count',
    domain: 'RETENTION',
    name: 'High Retention Risk Population',
    description: 'Count of members identified with HIGH retention risk (> 70% churn likelihood).',
    source: 'RetentionAnalysis',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'retention.elevated_risk_count': {
    key: 'retention.elevated_risk_count',
    domain: 'RETENTION',
    name: 'Elevated Retention Risk Population',
    description: 'Count of members identified with ELEVATED retention risk (40% - 70% churn likelihood).',
    source: 'RetentionAnalysis',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'memberships.read'],
  },
  'retention.follow_up_queue_count': {
    key: 'retention.follow_up_queue_count',
    domain: 'RETENTION',
    name: 'Pending Retention Tasks',
    description: 'Pending retention follow-up tasks waiting for staff intervention.',
    source: 'RetentionFollowUpTask',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'staff.read'],
  },

  // -------------------------------------------------------------
  // SALES DOMAIN (Day 40 Reused)
  // -------------------------------------------------------------
  'sales.new_leads': {
    key: 'sales.new_leads',
    domain: 'SALES',
    name: 'New Leads Captured',
    description: 'Count of new leads generated within the selected timeframe.',
    source: 'SalesIntelligenceService (Lead)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
  },
  'sales.qualified_leads': {
    key: 'sales.qualified_leads',
    domain: 'SALES',
    name: 'Qualified Leads',
    description: 'Count of leads that met authoritative qualification criteria.',
    source: 'SalesIntelligenceService (Lead / SalesOpportunity)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
  },
  'sales.conversions': {
    key: 'sales.conversions',
    domain: 'SALES',
    name: 'Sales Conversions',
    description: 'Count of opportunities/leads that converted to paid memberships in the period.',
    source: 'SalesIntelligenceService (SalesOpportunity)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
  },
  'sales.conversion_rate': {
    key: 'sales.conversion_rate',
    domain: 'SALES',
    name: 'Lead-to-Member Conversion Rate',
    description: 'Percentage of leads/closed opportunities that converted into active paying members.',
    source: 'SalesIntelligenceService (Calculated)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
    dataQualityRequirements: {
      minimumSampleThreshold: 5,
      caveats: ['Small sample warning if closed leads < 5.'],
    },
  },
  'sales.pipeline_value': {
    key: 'sales.pipeline_value',
    domain: 'SALES',
    name: 'Estimated Pipeline Value',
    description: 'Sum of monetary opportunity values across all active open opportunities.',
    source: 'SalesIntelligenceService (SalesOpportunity)',
    aggregation: 'SUM',
    unit: 'CURRENCY',
    requiresCurrency: true,
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
  },
  'sales.speed_to_lead': {
    key: 'sales.speed_to_lead',
    domain: 'SALES',
    name: 'Average Speed-to-Lead',
    description: 'Average duration in seconds between lead creation and initial outreach.',
    source: 'SalesIntelligenceService (Calculated)',
    aggregation: 'AVG',
    unit: 'SECONDS',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'leads.read'],
  },

  // -------------------------------------------------------------
  // FINANCE DOMAIN (Days 41-44 Reused)
  // -------------------------------------------------------------
  'finance.gross_revenue': {
    key: 'finance.gross_revenue',
    domain: 'FINANCE',
    name: 'Gross Cash-Basis Revenue',
    description: 'Total successful payment receipts before deductions, partitioned strictly by currency.',
    source: 'FinancialIntelligenceService (FinancialTransactionReference)',
    aggregation: 'SUM',
    unit: 'CURRENCY',
    requiresCurrency: true,
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'payments.read'],
  },
  'finance.refunds': {
    key: 'finance.refunds',
    domain: 'FINANCE',
    name: 'Total Refunds',
    description: 'Total processed refund deductions within the period, partitioned by currency.',
    source: 'FinancialIntelligenceService (FinancialTransactionReference)',
    aggregation: 'SUM',
    unit: 'CURRENCY',
    requiresCurrency: true,
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'payments.read'],
  },
  'finance.net_revenue': {
    key: 'finance.net_revenue',
    domain: 'FINANCE',
    name: 'Net Cash-Basis Revenue',
    description: 'Gross cash receipts minus refunds: Gross - Refunds.',
    source: 'FinancialIntelligenceService (Calculated)',
    aggregation: 'SUM',
    unit: 'CURRENCY',
    requiresCurrency: true,
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'payments.read'],
  },
  'finance.payment_success_rate': {
    key: 'finance.payment_success_rate',
    domain: 'FINANCE',
    name: 'Payment Gateway Success Rate',
    description: 'Successful payment transactions divided by total processed attempts (Succeeded + Failed) * 100.',
    source: 'FinancialIntelligenceService (PaymentTransaction)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'payments.read'],
  },
  'finance.outstanding_balance': {
    key: 'finance.outstanding_balance',
    domain: 'FINANCE',
    name: 'Total Outstanding Invoice Balance',
    description: 'Total balance remaining unpaid on OPEN and OVERDUE invoices, partitioned by currency.',
    source: 'FinancialIntelligenceService (Invoice)',
    aggregation: 'SUM',
    unit: 'CURRENCY',
    requiresCurrency: true,
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'invoices.read'],
  },
  'finance.collection_rate': {
    key: 'finance.collection_rate',
    domain: 'FINANCE',
    name: 'Billing Collection Rate',
    description: 'Total collected recurring billing amount divided by total billed amount * 100.',
    source: 'RecurringBillingService (BillingCycle)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'payments.read'],
  },

  // -------------------------------------------------------------
  // ATTENDANCE DOMAIN (Day 10 Reused)
  // -------------------------------------------------------------
  'attendance.total_visits': {
    key: 'attendance.total_visits',
    domain: 'ATTENDANCE',
    name: 'Total Facility Visits',
    description: 'Count of all recorded check-ins and completed attendance records.',
    source: 'AttendanceService (CheckIn & AttendanceRecord)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'door_access.read'],
  },
  'attendance.unique_visitors': {
    key: 'attendance.unique_visitors',
    domain: 'ATTENDANCE',
    name: 'Unique Visiting Members',
    description: 'Distinct member profiles that checked in at least once during the period.',
    source: 'AttendanceService (CheckIn & AttendanceRecord)',
    aggregation: 'DISTINCT_COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'door_access.read'],
  },
  'attendance.frequency': {
    key: 'attendance.frequency',
    domain: 'ATTENDANCE',
    name: 'Average Attendance Frequency',
    description: 'Average visits per active member during the timeframe: Total Visits / Active Members.',
    source: 'AttendanceService (Calculated)',
    aggregation: 'AVG',
    unit: 'SCORE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'door_access.read'],
  },

  // -------------------------------------------------------------
  // BOOKINGS DOMAIN (Days 8-9 Reused)
  // -------------------------------------------------------------
  'booking.total_bookings': {
    key: 'booking.total_bookings',
    domain: 'BOOKING',
    name: 'Class & Session Bookings',
    description: 'Total group class and appointment bookings confirmed in the period.',
    source: 'BookingsService (Booking)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'classes.read'],
  },
  'booking.average_class_fill_rate': {
    key: 'booking.average_class_fill_rate',
    domain: 'BOOKING',
    name: 'Average Class Fill Rate',
    description: 'Percentage of available class capacity filled across all scheduled sessions.',
    source: 'BookingsService (ClassSession & Booking)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'classes.read'],
  },
  'booking.no_show_rate': {
    key: 'booking.no_show_rate',
    domain: 'BOOKING',
    name: 'Booking No-Show Rate',
    description: 'Percentage of confirmed bookings marked as NO_SHOW.',
    source: 'BookingsService (Booking)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'classes.read'],
  },

  // -------------------------------------------------------------
  // TRAINING & PT DOMAIN (Days 12-15 Reused)
  // -------------------------------------------------------------
  'training.workout_adherence': {
    key: 'training.workout_adherence',
    domain: 'TRAINING',
    name: 'Workout Adherence Rate',
    description: 'Percentage of scheduled workouts logged as completed: Completed / Scheduled * 100.',
    source: 'WorkoutsService (Workout)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'workouts.read'],
  },
  'training.pt_sessions': {
    key: 'training.pt_sessions',
    domain: 'TRAINING',
    name: 'PT Sessions Conducted',
    description: 'Count of completed 1-on-1 personal training sessions.',
    source: 'PersonalTrainingService (PersonalTrainingSession)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'pt_sessions.read'],
  },

  // -------------------------------------------------------------
  // ENGAGEMENT DOMAIN (Day 25 Reused)
  // -------------------------------------------------------------
  'engagement.avg_score': {
    key: 'engagement.avg_score',
    domain: 'ENGAGEMENT',
    name: 'Average Engagement Score',
    description: 'Mean engagement score (0 - 100) across all active members in the organisation.',
    source: 'EngagementService (MemberEngagementProfile)',
    aggregation: 'AVG',
    unit: 'SCORE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'engagement.read'],
  },

  // -------------------------------------------------------------
  // COMMUNICATION DOMAIN (Days 28 & 39 Reused)
  // -------------------------------------------------------------
  'communication.delivery_rate': {
    key: 'communication.delivery_rate',
    domain: 'COMMUNICATION',
    name: 'Communication Delivery Rate',
    description: 'Delivered messages divided by total sent messages * 100.',
    source: 'CommunicationsService (Communication)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'communications.read'],
  },

  // -------------------------------------------------------------
  // AI OPERATIONAL DOMAIN
  // -------------------------------------------------------------
  'ai.total_requests': {
    key: 'ai.total_requests',
    domain: 'AI',
    name: 'Total AI Invocations',
    description: 'Count of AI platform requests executed across Receptionist, Sales, and Intelligence modules.',
    source: 'AIPlatform (AIRequest)',
    aggregation: 'COUNT',
    unit: 'COUNT',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'ai.read'],
  },
  'ai.receptionist_resolution_rate': {
    key: 'ai.receptionist_resolution_rate',
    domain: 'AI',
    name: 'AI Receptionist Resolution Rate',
    description: 'Percentage of receptionist inquiries resolved autonomously without staff handoff.',
    source: 'AIReceptionist (ReceptionistConversation)',
    aggregation: 'RATIO',
    unit: 'PERCENTAGE',
    supportsOutletScope: true,
    supportsOrganisationScope: true,
    supportsComparison: true,
    permissions: ['reports.read', 'ai.read'],
  },
};
