import { SalesMetricDefinitionDto } from '@fitcore/types';

export const MIN_SAMPLE_SIZE = 10;
export const DEFAULT_CACHE_TTL_MS = 5 * 60 * 1000; // 5 minutes

export const SALES_INTELLIGENCE_AUDIT_ACTIONS = {
  SALES_DASHBOARD_VIEWED: 'SALES_DASHBOARD_VIEWED',
  SALES_METRIC_VIEWED: 'SALES_METRIC_VIEWED',
  SALES_EXPORT_CREATED: 'SALES_EXPORT_CREATED',
  SALES_AI_INSIGHT_GENERATED: 'SALES_AI_INSIGHT_GENERATED',
  SALES_AI_INSIGHT_VIEWED: 'SALES_AI_INSIGHT_VIEWED',
} as const;

export const CANONICAL_METRIC_DEFINITIONS: SalesMetricDefinitionDto[] = [
  {
    name: 'newLeads',
    displayName: 'New Leads',
    description: 'Total number of prospective member leads created within the selected time period.',
    formula: 'COUNT(leads WHERE createdAt >= startDate AND createdAt <= endDate)',
    source: 'Lead domain (Day 33)',
    denominator: 'N/A (Count metric)',
    timeWindow: 'Selected date range (UTC converted from outlet timezone)',
    limitations: 'Does not count rejected spam or duplicate lead merges.',
  },
  {
    name: 'qualifiedLeads',
    displayName: 'Qualified Leads',
    description: 'Leads reaching authoritative QUALIFIED, HIGH_INTENT, or READY_FOR_NEXT_STEP status.',
    formula: 'COUNT(leads WHERE qualificationProfile.qualificationStatus = "QUALIFIED" OR qualificationProfile.isHighIntent = true)',
    source: 'Lead Qualification Profile domain (Day 38)',
    denominator: 'N/A (Count metric)',
    timeWindow: 'Selected date range based on lead qualification timestamp',
    limitations: 'Excludes leads currently in qualifying or needing human review.',
  },
  {
    name: 'openOpportunities',
    displayName: 'Open Opportunities',
    description: 'Active commercial opportunities in the pipeline not marked CONVERTED or LOST.',
    formula: 'COUNT(salesOpportunities WHERE currentStage NOT IN ("CONVERTED", "LOST"))',
    source: 'Sales Opportunity domain (Day 37)',
    denominator: 'N/A (Count metric)',
    timeWindow: 'Current active state within tenant boundary',
    limitations: 'Includes stale opportunities that have not reached explicit loss stage.',
  },
  {
    name: 'conversions',
    displayName: 'Conversions',
    description: 'Leads or opportunities that resulted in verified member conversion or active membership.',
    formula: 'COUNT(salesOpportunities WHERE currentStage = "CONVERTED" AND convertedAt >= startDate AND convertedAt <= endDate)',
    source: 'Sales Opportunity & MemberMembership domain (Day 37 / Day 4)',
    denominator: 'N/A (Count metric)',
    timeWindow: 'Selected date range based on convertedAt',
    limitations: 'Observational tracking. Financial billing reconciliation handled in Day 41.',
  },
  {
    name: 'conversionRate',
    displayName: 'Overall Conversion Rate',
    description: 'Percentage of leads created in the period that resulted in authoritative conversion.',
    formula: 'conversions / totalLeadsCreated * 100',
    source: 'Lead & Opportunity domains (Days 33, 37)',
    denominator: 'Total leads created in the period',
    timeWindow: 'Cohort period based on lead creation',
    limitations: 'Small samples (<10 records) yield INSUFFICIENT_DATA to prevent statistical distortion.',
  },
  {
    name: 'responseRate',
    displayName: 'Inbound Response Rate',
    description: 'Proportion of prospects receiving outbound contact who replied with an inbound response.',
    formula: 'COUNT(prospects with inbound reply) / COUNT(prospects with outbound contact) * 100',
    source: 'FollowUpResponse, CommunicationEvent, SalesActivity domains (Days 28, 37, 39)',
    denominator: 'Total unique prospects sent outbound communications',
    timeWindow: 'Selected date range',
    limitations: 'Does not count delivery or read receipts as active responses.',
  },
  {
    name: 'speedToLead',
    displayName: 'Speed to Lead',
    description: 'Elapsed seconds from lead record creation to first outbound contact by staff or AI.',
    formula: 'AVG(firstOutboundActivityAt - leadCreatedAt) in seconds',
    source: 'Lead & SalesActivity / Communication domains (Days 33, 28, 37)',
    denominator: 'Contacted leads with valid timestamps',
    timeWindow: 'Selected date range',
    limitations: 'Distinguishes AI response, Staff response, and Automated Follow-up sources.',
  },
  {
    name: 'pipelineValue',
    displayName: 'Estimated Pipeline Value',
    description: 'Aggregate estimated commercial value of all open opportunities.',
    formula: 'SUM(estimatedValue WHERE currentStage NOT IN ("CONVERTED", "LOST"))',
    source: 'Sales Opportunity domain (Day 37)',
    denominator: 'N/A (Currency sum)',
    timeWindow: 'Current snapshot',
    limitations: 'Commercial estimate only; does not represent realized cash revenue (Day 41).',
  },
  {
    name: 'followUpResponseRate',
    displayName: 'Follow-Up Response Rate',
    description: 'Proportion of follow-up sequence enrollments receiving an inbound customer response.',
    formula: 'COUNT(enrollments with response) / COUNT(enrollments started) * 100',
    source: 'FollowUpEnrollment & FollowUpResponse domains (Day 39)',
    denominator: 'Total enrollments started in period',
    timeWindow: 'Selected date range',
    limitations: 'Non-causal observational attribution.',
  },
  {
    name: 'receptionistToLeadRate',
    displayName: 'Receptionist Conversation to Lead Rate',
    description: 'Percentage of AI Receptionist conversations resulting in a captured lead.',
    formula: 'leadsCreatedFromReceptionist / totalReceptionistConversations * 100',
    source: 'ReceptionistInteraction & Lead domains (Days 33, 35)',
    denominator: 'Total receptionist conversations',
    timeWindow: 'Selected date range',
    limitations: 'Excludes conversations with existing verified gym members.',
  },
];
