/**
 * Constants for FitCore AI Reactivation & Member Recovery (Day 27)
 */

export const AI_REACTIVATION_FEATURE = 'AI_REACTIVATION';
export const REACTIVATION_PROMPT_KEY = 'reactivation.v1';
export const REACTIVATION_PROMPT_VERSION = 1;

// Default Deterministic Thresholds (Configurable & Centralized)
export const REACTIVATION_THRESHOLDS = {
  MINIMUM_INACTIVITY_DAYS: 14,
  HIGH_INACTIVITY_DAYS: 28,
  EXTREME_INACTIVITY_DAYS: 60,
  ENGAGEMENT_DECLINE_THRESHOLD_PCT: 40,
  HIGH_DECLINE_THRESHOLD_PCT: 70,
  MINIMUM_HISTORICAL_OBSERVATIONS: 3,
  REENGAGEMENT_WINDOW_DAYS: 14,
  MINIMUM_RECOVERY_ATTENDANCE: 2,
  MINIMUM_RECOVERY_WORKOUTS: 1,
  DEFAULT_PLAN_EXPIRY_DAYS: 14,
} as const;

// Cache TTL
export const REACTIVATION_ANALYSIS_CACHE_TTL_SECONDS = 3600; // 1 hour
export const REACTIVATION_QUEUE_CACHE_TTL_SECONDS = 300;     // 5 minutes
export const REACTIVATION_SUMMARY_CACHE_TTL_SECONDS = 600;   // 10 minutes

// Domain Events (Internal Event Bus / Observability)
export const REACTIVATION_DOMAIN_EVENTS = {
  MEMBER_ELIGIBLE: 'MEMBER_REACTIVATION_ELIGIBLE',
  RECOMMENDED: 'REACTIVATION_RECOMMENDED',
  PLAN_APPROVED: 'RECOVERY_PLAN_APPROVED',
  PLAN_STARTED: 'RECOVERY_PLAN_STARTED',
  REENGAGEMENT_DETECTED: 'MEMBER_REENGAGEMENT_DETECTED',
  MEMBER_REENGAGED: 'MEMBER_REENGAGED',
  PLAN_COMPLETED: 'RECOVERY_PLAN_COMPLETED',
  PLAN_EXPIRED: 'RECOVERY_PLAN_EXPIRED',
} as const;

// Audit Event Actions (Auditing without sensitive medical/health leaks)
export const REACTIVATION_AUDIT_ACTIONS = {
  ANALYSIS_VIEWED: 'REACTIVATION_ANALYSIS_VIEWED',
  RECOMMENDATION_GENERATED: 'REACTIVATION_RECOMMENDATION_GENERATED',
  RECOVERY_PLAN_CREATED: 'RECOVERY_PLAN_CREATED',
  RECOVERY_PLAN_APPROVED: 'RECOVERY_PLAN_APPROVED',
  RECOVERY_PLAN_REJECTED: 'RECOVERY_PLAN_REJECTED',
  RECOVERY_PLAN_STARTED: 'RECOVERY_PLAN_STARTED',
  RECOVERY_PLAN_COMPLETED: 'RECOVERY_PLAN_COMPLETED',
  RECOVERY_PLAN_DISMISSED: 'RECOVERY_PLAN_DISMISSED',
  REENGAGEMENT_DETECTED: 'MEMBER_REENGAGEMENT_DETECTED',
  FEEDBACK_SUBMITTED: 'REACTIVATION_AI_FEEDBACK_SUBMITTED',
} as const;

// Authorized Staff Roles for Reactivation & Member Recovery
export const REACTIVATION_STAFF_ROLES = [
  'SUPERADMIN',
  'ORGANISATION_OWNER',
  'OUTLET_MANAGER',
  'TRAINER',
  'RECEPTION',
] as const;
