/**
 * Daily Check-In Enums & Statuses
 */

export enum DailyCheckInStatus {
  PENDING = 'PENDING',
  STARTED = 'STARTED',
  COMPLETED = 'COMPLETED',
  SKIPPED = 'SKIPPED',
  EXPIRED = 'EXPIRED',
}

export enum EnergyLevel {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
}

export enum WellbeingMood {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  NEUTRAL = 'NEUTRAL',
  GOOD = 'GOOD',
  VERY_GOOD = 'VERY_GOOD',
}

export enum SleepQuality {
  VERY_POOR = 'VERY_POOR',
  POOR = 'POOR',
  FAIR = 'FAIR',
  GOOD = 'GOOD',
  EXCELLENT = 'EXCELLENT',
}

export enum SorenessLevel {
  NONE = 'NONE',
  MILD = 'MILD',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

export enum StressLevel {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

export enum MotivationLevel {
  VERY_LOW = 'VERY_LOW',
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  VERY_HIGH = 'VERY_HIGH',
}

export enum DailyReadinessCategory {
  OPTIMAL = 'OPTIMAL',
  MODERATE = 'MODERATE',
  RECOVERY_FOCUSED = 'RECOVERY_FOCUSED',
}

export enum DailyRecommendationType {
  TRAINING = 'TRAINING',
  RECOVERY = 'RECOVERY',
  NUTRITION = 'NUTRITION',
  HYDRATION = 'HYDRATION',
  CONSISTENCY = 'CONSISTENCY',
  GOAL = 'GOAL',
  ATTENDANCE = 'ATTENDANCE',
  ENGAGEMENT = 'ENGAGEMENT',
  SUPPORT = 'SUPPORT',
}

export enum DailyCheckInTrend {
  ENERGY_DECLINING = 'ENERGY_DECLINING',
  ENERGY_IMPROVING = 'ENERGY_IMPROVING',
  SLEEP_DECLINING = 'SLEEP_DECLINING',
  SORENESS_INCREASING = 'SORENESS_INCREASING',
  MOTIVATION_DECLINING = 'MOTIVATION_DECLINING',
  TRAINING_CONSISTENCY_IMPROVING = 'TRAINING_CONSISTENCY_IMPROVING',
  TRAINING_CONSISTENCY_DECLINING = 'TRAINING_CONSISTENCY_DECLINING',
  NUTRITION_LOGGING_IMPROVING = 'NUTRITION_LOGGING_IMPROVING',
  NUTRITION_LOGGING_DECLINING = 'NUTRITION_LOGGING_DECLINING',
}
