/**
 * FitCore — Day 44: AI Finance Assistant Constants & Canonical Definitions
 */

export const FINANCE_ASSISTANT_CONSTANTS = {
  FEATURE_NAME: 'FINANCE_ASSISTANT',
  DEFAULT_MODEL: 'fitcore-finance-intelligence-agent',
  DEFAULT_CURRENCY: 'AUD',
  SUPPORTED_CURRENCIES: ['AUD', 'USD', 'NPR', 'EUR', 'GBP', 'CAD', 'NZD', 'SGD'],
  CACHE_TTL_SECONDS: 300, // 5 minutes
  MAX_CONVERSATION_HISTORY: 10,
  STATE_TOKEN_TTL_MS: 10 * 60 * 1000,
} as const;

export const CANONICAL_FINANCIAL_METRICS = {
  GROSS_REVENUE: {
    name: 'Gross Revenue',
    definition: 'Actual financial amount recognised by the FitCore financial intelligence layer according to the configured revenue basis (cash-basis: payments received; accrual-basis: invoices issued).',
    formula: 'Sum of all successful payments or issued invoices in period',
    source: 'Day 41 Financial Intelligence / Day 6 Payments',
  },
  REFUNDS: {
    name: 'Refunds',
    definition: 'Total successful refund amounts processed and debited from gym revenue during the period.',
    formula: 'Sum of all successful refund transactions in period',
    source: 'Day 41 Financial Intelligence / Day 6 Payments',
  },
  NET_REVENUE: {
    name: 'Net Revenue',
    definition: 'Gross Revenue minus successful refunds.',
    formula: 'Gross Revenue - Refunds',
    source: 'Day 41 Financial Intelligence',
  },
  MEMBERSHIP_REVENUE: {
    name: 'Membership Revenue',
    definition: 'Actual financial transactions and payments attributable to membership plans and recurring subscriptions. Excludes retail, personal training, and casual passes.',
    formula: 'Sum of payments/invoices linked to memberMembershipId or MEMBERSHIP category',
    source: 'Day 41 Financial Intelligence / Day 42 Recurring Billing',
  },
  OUTSTANDING_BALANCE: {
    name: 'Outstanding Balance',
    definition: 'Cumulative unpaid financial debt from OPEN or OVERDUE invoices that have not been marked VOID or UNCOLLECTIBLE.',
    formula: 'Sum of (Invoice.totalMinor - Invoice.amountPaidMinor) for open/overdue invoices',
    source: 'Day 41 Financial Intelligence / Day 6 Invoices',
  },
  COLLECTION_RATE: {
    name: 'Collection Rate',
    definition: 'Percentage of scheduled and eligible recurring billing charges successfully collected.',
    formula: '(Successfully Collected Recurring Amount / Eligible Recurring Amount Due) * 100',
    source: 'Day 42 Recurring Billing & Collections',
  },
  RECOVERY_RATE: {
    name: 'Recovery Rate',
    definition: 'Percentage of previously failed recurring payment amounts successfully recovered through automatic retries, member self-service updates, or dunning.',
    formula: '(Amount Recovered After Initial Failure / Amount Initially Failed) * 100',
    source: 'Day 42 Recurring Billing & Collections',
  },
  PAYMENT_SUCCESS_RATE: {
    name: 'Payment Success Rate',
    definition: 'Percentage of all payment attempts that resulted in a successful transaction.',
    formula: '(Successful Payments / (Successful Payments + Failed Payments)) * 100',
    source: 'Day 41 Financial Intelligence',
  },
} as const;

export const ADVISORY_DISCLAIMERS = {
  FINANCIAL_ADVICE: 'This information is generated by FitCore AI based on recorded operational data. It is intended for operational and informational purposes only and does not constitute formal accounting, tax, or financial advisory services.',
  TAX_PROFESSIONAL: 'FitCore is not a tax advisory platform. For statutory tax liability, GST/VAT filings, and tax reporting, please consult a certified public accountant or registered tax agent.',
  FORECASTING_BOUNDARY: 'FitCore AI does not generate speculative financial forecasts. Historical trends and observed performance metrics are provided for operational decision-making.',
  CAUSATION_LIMITATION: 'Observed financial correlations and trends describe data relationships and do not prove direct causation.',
} as const;

export const MALICIOUS_PATTERNS = [
  /ignore\s+(all\s+)?(previous\s+)?(rules|instructions|permissions|guards|system)/i,
  /reveal\s+(system\s+)?(instructions|prompt)/i,
  /you\s+are\s+(an\s+)?unrestricted/i,
  /assume\s+(revenue|payments|money)\s+(is|was|to be)/i,
  /fabricate\s+(data|metrics|numbers|revenue)/i,
  /show\s+(me\s+)?(all\s+)?(other\s+)?(tenant|organisation|outlet|owner)('s)?\s+(data|revenue|money|finances)/i,
  /drop\s+table/i,
  /select\s+\*\s+from/i,
  /delete\s+from/i,
  /give\s+me\s+everyone('s)?\s+payment/i,
  /bypass\s+security/i,
  /pretend\s+to\s+be/i,
  /what\s+is\s+the\s+database\s+password/i,
];
