import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../database/prisma.service';
import {
  PrivacyDataCategory,
  PrivacyDataClassification,
  PrivacyDataPurpose,
  PrivacyDataAssetDto,
  DeletionStrategyAction,
} from '@fitcore/types';

export interface DataAssetDefinition {
  category: PrivacyDataCategory;
  domain: string;
  entity: string;
  fieldPath?: string;
  classification: PrivacyDataClassification;
  purpose: PrivacyDataPurpose;
  source: string;
  storageLocation: string;
  retentionPolicy: string;
  deletionPolicy: DeletionStrategyAction;
  exportable: boolean;
  deletable: boolean;
  requiresConsent: boolean;
  sensitive: boolean;
  description: string;
}

export const BASE_DATA_CATALOG: DataAssetDefinition[] = [
  {
    category: 'IDENTITY',
    domain: 'auth',
    entity: 'User',
    fieldPath: 'email, phone, fullName',
    classification: 'PERSONAL',
    purpose: 'ACCOUNT_MANAGEMENT',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_ACCOUNT',
    deletionPolicy: 'ANONYMIZE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Account credentials and basic contact identification details.',
  },
  {
    category: 'PROFILE',
    domain: 'members',
    entity: 'MemberProfile',
    fieldPath: 'dateOfBirth, gender, emergencyContact',
    classification: 'PERSONAL',
    purpose: 'MEMBERSHIP_MANAGEMENT',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Member personal profile details, timezone, and emergency contacts.',
  },
  {
    category: 'HEALTH',
    domain: 'health',
    entity: 'HealthScreening',
    fieldPath: 'conditions, medications, bloodPressure, clearanceRequired',
    classification: 'HIGHLY_SENSITIVE',
    purpose: 'HEALTH_SCREENING',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: '7_YEARS_LEGAL_HEALTH',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: true,
    sensitive: true,
    description: 'Pre-exercise health screening questionnaires, PAR-Q responses, and medical risk indicators.',
  },
  {
    category: 'MEDICAL_DOCUMENT',
    domain: 'health',
    entity: 'MedicalClearance',
    fieldPath: 'documentUrl, doctorName, clearanceStatus',
    classification: 'HIGHLY_SENSITIVE',
    purpose: 'HEALTH_SCREENING',
    source: 'THIRD_PARTY_MEDICAL',
    storageLocation: 'OBJECT_STORAGE',
    retentionPolicy: '7_YEARS_LEGAL_HEALTH',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: true,
    sensitive: true,
    description: 'Physician medical clearance letters and clinical certificates.',
  },
  {
    category: 'WEARABLE',
    domain: 'wearables',
    entity: 'HealthDataRecord',
    fieldPath: 'heartRate, sleep, steps, activeCalories, spo2',
    classification: 'HIGHLY_SENSITIVE',
    purpose: 'WEARABLE_SYNC',
    source: 'DEVICE_SYNC',
    storageLocation: 'POSTGRES',
    retentionPolicy: '2_YEARS',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: true,
    sensitive: true,
    description: 'Continuous biometric telemetry, resting heart rate, sleep architecture, and daily energy expenditure.',
  },
  {
    category: 'FITNESS',
    domain: 'progress',
    entity: 'BodyMeasurement',
    fieldPath: 'weight, bodyFatPercentage, circumferences',
    classification: 'PERSONAL',
    purpose: 'TRAINING',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Body anthropometric metrics, weight tracking, and personal fitness records.',
  },
  {
    category: 'TRAINING',
    domain: 'training-plans',
    entity: 'Workout',
    fieldPath: 'exercises, sets, reps, weight, rpe',
    classification: 'PERSONAL',
    purpose: 'TRAINING',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Workout logs, exercise completion records, and trainer programming notes.',
  },
  {
    category: 'NUTRITION',
    domain: 'nutrition',
    entity: 'FoodLog',
    fieldPath: 'meals, calories, macros, water',
    classification: 'PERSONAL',
    purpose: 'NUTRITION',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Dietary intake, macronutrient breakdowns, meal logs, and hydration tracking.',
  },
  {
    category: 'ATTENDANCE',
    domain: 'attendance',
    entity: 'AttendanceRecord',
    fieldPath: 'checkInTime, checkOutTime, facilityLocation',
    classification: 'INTERNAL',
    purpose: 'ACCESS_CONTROL',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '3_YEARS',
    deletionPolicy: 'ANONYMIZE',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: false,
    description: 'Physical turnstile check-ins, facility access timestamps, and outlet presence logs.',
  },
  {
    category: 'BOOKING',
    domain: 'bookings',
    entity: 'Booking',
    fieldPath: 'classId, instructorId, bookedAt, status',
    classification: 'INTERNAL',
    purpose: 'BOOKING',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: '3_YEARS',
    deletionPolicy: 'ANONYMIZE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Class reservations, personal training appointments, and waitlist allocations.',
  },
  {
    category: 'MEMBERSHIP',
    domain: 'memberships',
    entity: 'MemberMembership',
    fieldPath: 'tier, startDate, endDate, autoRenew',
    classification: 'INTERNAL',
    purpose: 'MEMBERSHIP_MANAGEMENT',
    source: 'STAFF_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: '7_YEARS_TAX',
    deletionPolicy: 'RETAIN',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: false,
    description: 'Membership contract terms, subscription status, and tier entitlements.',
  },
  {
    category: 'PAYMENT',
    domain: 'payments',
    entity: 'PaymentTransaction',
    fieldPath: 'amount, currency, status, gatewayRef, cardBrand, last4',
    classification: 'SENSITIVE',
    purpose: 'PAYMENT_PROCESSING',
    source: 'THIRD_PARTY_GATEWAY',
    storageLocation: 'POSTGRES',
    retentionPolicy: '7_YEARS_TAX',
    deletionPolicy: 'RETAIN',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: true,
    description: 'Transaction records, masked payment card details (last 4 digits only), and billing history.',
  },
  {
    category: 'FINANCIAL',
    domain: 'payments',
    entity: 'Invoice',
    fieldPath: 'invoiceNumber, subtotal, taxAmount, totalAmount',
    classification: 'SENSITIVE',
    purpose: 'LEGAL_COMPLIANCE',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '7_YEARS_TAX',
    deletionPolicy: 'RETAIN',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: true,
    description: 'Invoices, credit notes, accounting ledger postings, and tax statements.',
  },
  {
    category: 'COMMUNICATION',
    domain: 'communication',
    entity: 'Communication',
    fieldPath: 'channel, recipient, subject, deliveredAt',
    classification: 'PERSONAL',
    purpose: 'COMMUNICATION',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '1_YEAR',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Notification delivery history across email, SMS, WhatsApp, and push channels.',
  },
  {
    category: 'AI_INTERACTION',
    domain: 'ai',
    entity: 'AIRequest',
    fieldPath: 'feature, queryPreview, tokenCount, latencyMs',
    classification: 'PERSONAL',
    purpose: 'AI_PERSONALIZATION',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: '90_DAYS',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: true,
    sensitive: false,
    description: 'Fitness coach chats, nutrition recommendations, and automated workout generation logs.',
  },
  {
    category: 'ENGAGEMENT',
    domain: 'engagement',
    entity: 'MemberEngagementProfile',
    fieldPath: 'score, streakDays, totalWorkouts, badges',
    classification: 'INTERNAL',
    purpose: 'MEMBERSHIP_MANAGEMENT',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Gamification metrics, attendance streaks, challenge badges, and reward credits.',
  },
  {
    category: 'RETENTION',
    domain: 'retention',
    entity: 'RetentionAnalysis',
    fieldPath: 'riskTier, churnProbability, primaryRiskFactor',
    classification: 'INTERNAL',
    purpose: 'ANALYTICS',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '1_YEAR',
    deletionPolicy: 'ANONYMIZE',
    exportable: false,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Internal algorithmic churn risk predictions and outreach intervention flags.',
  },
  {
    category: 'SECURITY',
    domain: 'security',
    entity: 'SecurityEvent',
    fieldPath: 'eventType, severity, ipAddress, userAgent',
    classification: 'INTERNAL',
    purpose: 'SECURITY',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '2_YEARS_SECURITY',
    deletionPolicy: 'RETAIN',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: false,
    description: 'Authentication logs, MFA verification events, session audits, and suspicious access alerts.',
  },
  {
    category: 'DEVICE',
    domain: 'security',
    entity: 'UserDevice',
    fieldPath: 'deviceName, platform, browser, lastSeenAt',
    classification: 'PERSONAL',
    purpose: 'SECURITY',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_ACCOUNT',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Registered user hardware devices, browser fingerprints, and mobile operating system metadata.',
  },
  {
    category: 'AUDIT',
    domain: 'audit',
    entity: 'AuditLog',
    fieldPath: 'action, entityType, entityId, timestamp',
    classification: 'INTERNAL',
    purpose: 'LEGAL_COMPLIANCE',
    source: 'SYSTEM_GENERATED',
    storageLocation: 'POSTGRES',
    retentionPolicy: '7_YEARS_LEGAL',
    deletionPolicy: 'RETAIN',
    exportable: false,
    deletable: false,
    requiresConsent: false,
    sensitive: false,
    description: 'Administrative change audit trail and staff action records.',
  },
  {
    category: 'DOCUMENT',
    domain: 'documents',
    entity: 'MemberDocument',
    fieldPath: 'documentType, storageKey, mimeType',
    classification: 'SENSITIVE',
    purpose: 'ACCOUNT_MANAGEMENT',
    source: 'USER_INPUT',
    storageLocation: 'OBJECT_STORAGE',
    retentionPolicy: 'DURATION_OF_MEMBERSHIP',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: true,
    description: 'Signed membership agreements, identity verification copies, and uploaded onboarding forms.',
  },
  {
    category: 'CONSENT',
    domain: 'consent',
    entity: 'ConsentRecord',
    fieldPath: 'consentType, version, status, consentedAt, withdrawnAt',
    classification: 'INTERNAL',
    purpose: 'LEGAL_COMPLIANCE',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'INDEFINITE_LEGAL_EVIDENCE',
    deletionPolicy: 'RETAIN',
    exportable: true,
    deletable: false,
    requiresConsent: false,
    sensitive: false,
    description: 'Immutable legal consent logs, policy version acknowledgments, and withdrawal timestamps.',
  },
  {
    category: 'MARKETING',
    domain: 'communications',
    entity: 'CommunicationPreference',
    fieldPath: 'channel, type, enabled',
    classification: 'PERSONAL',
    purpose: 'MARKETING',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_ACCOUNT',
    deletionPolicy: 'DELETE',
    exportable: true,
    deletable: true,
    requiresConsent: true,
    sensitive: false,
    description: 'Marketing campaign opt-ins, promotional messaging channels, and discount notification preferences.',
  },
  {
    category: 'CONTACT',
    domain: 'members',
    entity: 'MemberProfile',
    fieldPath: 'phone, emergencyPhone',
    classification: 'PERSONAL',
    purpose: 'ACCOUNT_MANAGEMENT',
    source: 'USER_INPUT',
    storageLocation: 'POSTGRES',
    retentionPolicy: 'DURATION_OF_ACCOUNT',
    deletionPolicy: 'ANONYMIZE',
    exportable: true,
    deletable: true,
    requiresConsent: false,
    sensitive: false,
    description: 'Direct contact numbers, secondary telephone lines, and emergency call contacts.',
  },
];

@Injectable()
export class PrivacyCatalogService {
  private readonly logger = new Logger(PrivacyCatalogService.name);

  constructor(private readonly prisma: PrismaService) {}

  /**
   * Initializes or refreshes default catalog assets for an organisation.
   */
  async ensureCatalogInitialized(organisationId?: string): Promise<void> {
    const existing = await this.prisma.privacyDataAsset.count({
      where: organisationId ? { organisationId } : { organisationId: null },
    });

    if (existing > 0) return;

    for (const def of BASE_DATA_CATALOG) {
      await this.prisma.privacyDataAsset.create({
        data: {
          organisationId: organisationId || null,
          category: def.category,
          domain: def.domain,
          entity: def.entity,
          fieldPath: def.fieldPath,
          classification: def.classification,
          purpose: def.purpose,
          source: def.source,
          storageLocation: def.storageLocation,
          retentionPolicy: def.retentionPolicy,
          deletionPolicy: def.deletionPolicy,
          exportable: def.exportable,
          deletable: def.deletable,
          requiresConsent: def.requiresConsent,
          sensitive: def.sensitive,
          description: def.description,
        },
      });
    }

    this.logger.log(`Initialized privacy data catalog with ${BASE_DATA_CATALOG.length} assets`);
  }

  /**
   * Returns all cataloged data assets for the organisation (or platform defaults).
   */
  async getCatalog(organisationId?: string): Promise<PrivacyDataAssetDto[]> {
    await this.ensureCatalogInitialized(organisationId);

    const assets = await this.prisma.privacyDataAsset.findMany({
      where: organisationId
        ? { OR: [{ organisationId }, { organisationId: null }] }
        : { organisationId: null },
      orderBy: { category: 'asc' },
    });

    return assets.map((a) => ({
      id: a.id,
      organisationId: a.organisationId,
      category: a.category as PrivacyDataCategory,
      domain: a.domain,
      entity: a.entity,
      fieldPath: a.fieldPath,
      classification: a.classification as PrivacyDataClassification,
      purpose: a.purpose as PrivacyDataPurpose,
      source: a.source,
      storageLocation: a.storageLocation,
      retentionPolicy: a.retentionPolicy,
      deletionPolicy: a.deletionPolicy as DeletionStrategyAction,
      exportable: a.exportable,
      deletable: a.deletable,
      requiresConsent: a.requiresConsent,
      sensitive: a.sensitive,
      description: a.description,
      createdAt: a.createdAt.toISOString(),
      updatedAt: a.updatedAt.toISOString(),
    }));
  }

  /**
   * Retrieves definition for a specific category.
   */
  getCategoryDefinition(category: PrivacyDataCategory): DataAssetDefinition | undefined {
    return BASE_DATA_CATALOG.find((a) => a.category === category);
  }

  /**
   * Returns human-readable summary for member-facing UI.
   */
  getHumanReadableCategories(): { category: PrivacyDataCategory; title: string; explanation: string }[] {
    return [
      {
        category: 'PROFILE',
        title: 'Your Profile & Identity',
        explanation: 'Your name, contact information, date of birth, and emergency contacts to manage your gym membership.',
      },
      {
        category: 'MEMBERSHIP',
        title: 'Memberships & Passes',
        explanation: 'Your active membership plans, access passes, renewal dates, and contracted terms.',
      },
      {
        category: 'TRAINING',
        title: 'Workouts & Training Plans',
        explanation: 'Your workout logs, exercise performance, personal records, and trainer programming.',
      },
      {
        category: 'NUTRITION',
        title: 'Meals & Nutrition Tracking',
        explanation: 'Your daily food logs, macronutrient goals, water intake, and dietary preferences.',
      },
      {
        category: 'HEALTH',
        title: 'Health & Medical Safety',
        explanation: 'Pre-exercise health screening responses and medical clearance documents to ensure safe training.',
      },
      {
        category: 'WEARABLE',
        title: 'Connected Wearables',
        explanation: 'Heart rate, sleep tracking, steps, and activity synchronized from Apple Health, Garmin, Whoop, or Fitbit.',
      },
      {
        category: 'AI_INTERACTION',
        title: 'AI Coaching & Insights',
        explanation: 'Conversations with AI fitness coaches, personalized workout suggestions, and daily check-in insights.',
      },
      {
        category: 'BOOKING',
        title: 'Class & Session Bookings',
        explanation: 'Upcoming and past class bookings, trainer appointments, and attendance history.',
      },
      {
        category: 'PAYMENT',
        title: 'Invoices & Billing',
        explanation: 'Payment transaction history, membership dues receipts, and secure billing references.',
      },
      {
        category: 'COMMUNICATION',
        title: 'Communications & Messages',
        explanation: 'Important notifications, gym announcements, reminders, and customer support messages.',
      },
    ];
  }
}
