export const COMMUNICATION_ERROR_CODES = {
  INVALID_RECIPIENT: 'INVALID_RECIPIENT',
  MISSING_CONSENT: 'MISSING_CONSENT',
  OPTED_OUT: 'OPTED_OUT',
  INVALID_TEMPLATE: 'INVALID_TEMPLATE',
  PROVIDER_UNAVAILABLE: 'PROVIDER_UNAVAILABLE',
  PROVIDER_REJECTED: 'PROVIDER_REJECTED',
  RATE_LIMITED: 'RATE_LIMITED',
  MESSAGE_EXPIRED: 'MESSAGE_EXPIRED',
  DUPLICATE_MESSAGE: 'DUPLICATE_MESSAGE',
  UNAUTHORIZED: 'UNAUTHORIZED',
} as const;

export const COMMUNICATION_AUDIT_ACTIONS = {
  CREATED: 'COMMUNICATION_CREATED',
  APPROVED: 'COMMUNICATION_APPROVED',
  QUEUED: 'COMMUNICATION_QUEUED',
  SENT: 'COMMUNICATION_SENT',
  DELIVERED: 'COMMUNICATION_DELIVERED',
  READ: 'COMMUNICATION_READ',
  FAILED: 'COMMUNICATION_FAILED',
  SUPPRESSED: 'COMMUNICATION_SUPPRESSED',
  CANCELLED: 'COMMUNICATION_CANCELLED',
  UNSUBSCRIBED: 'COMMUNICATION_UNSUBSCRIBED',
  TEMPLATE_CREATED: 'COMMUNICATION_TEMPLATE_CREATED',
  TEMPLATE_UPDATED: 'COMMUNICATION_TEMPLATE_UPDATED',
  PREFERENCE_UPDATED: 'COMMUNICATION_PREFERENCE_UPDATED',
} as const;

export const TRANSACTIONAL_COMMUNICATION_TYPES = [
  'TRANSACTIONAL',
  'SECURITY',
  'SYSTEM',
  'OPERATIONAL',
] as const;

export const DEFAULT_QUIET_HOURS = {
  START: '21:00',
  END: '08:00',
  TIMEZONE: 'UTC',
} as const;

export const DEFAULT_RETRY_CONFIG = {
  MAX_ATTEMPTS: 3,
  INITIAL_BACKOFF_MS: 1000,
  BACKOFF_FACTOR: 2,
  MAX_BACKOFF_MS: 30000,
} as const;

export const RATE_LIMIT_CONFIG = {
  MAX_PER_RECIPIENT_PER_MINUTE: 100,
  MAX_PER_ORGANISATION_PER_MINUTE: 1000,
  DUPLICATE_SUPPRESSION_WINDOW_SECONDS: 60,
};
